export type StickerPreset = {
  id: string
  label: string
  emoji: string
}

export const STICKER_PRESETS: StickerPreset[] = [
  { id: 'wow', label: 'WOW', emoji: '🔥' },
  { id: 'sale', label: 'SALE', emoji: '💸' },
  { id: 'star', label: 'TOP', emoji: '⭐' },
  { id: 'mint', label: 'MINT', emoji: '💎' },
  { id: 'hook', label: 'HOOK', emoji: '🎯' },
  { id: 'fast', label: 'FAST', emoji: '⚡' },
  { id: 'trend', label: 'TREND', emoji: '📈' },
  { id: 'cut', label: 'CUT', emoji: '✂️' },
  { id: 'react', label: 'REACT', emoji: '😮' },
  { id: 'win', label: 'WIN', emoji: '🏆' },
  { id: 'shop', label: 'SHOP', emoji: '🛍️' },
  { id: 'play', label: 'PLAY', emoji: '▶️' },
  { id: 'boom', label: 'BOOM', emoji: '💥' },
  { id: 'new', label: 'NEW', emoji: '🆕' },
  { id: 'idea', label: 'IDEA', emoji: '💡' },
  { id: 'pro', label: 'PRO', emoji: '✅' },
  { id: 'danger', label: 'ALERT', emoji: '🚨' },
  { id: 'spark', label: 'SPARK', emoji: '✨' },
  { id: 'music', label: 'BEAT', emoji: '🎵' },
  { id: 'cam', label: 'REC', emoji: '📹' },
  { id: 'goal', label: 'GOAL', emoji: '🥅' },
  { id: 'money', label: 'CASH', emoji: '💰' },
  { id: 'rocket', label: 'GO', emoji: '🚀' },
  { id: 'brain', label: 'SMART', emoji: '🧠' },
  { id: 'fire2', label: 'HOT', emoji: '♨️' },
  { id: 'drop', label: 'DROP', emoji: '📦' },
  { id: 'plus', label: 'PLUS', emoji: '➕' },
  { id: 'minus', label: 'LESS', emoji: '➖' },
  { id: 'check', label: 'OK', emoji: '✔️' },
  { id: 'cross', label: 'NO', emoji: '❌' },
  { id: 'eyes', label: 'LOOK', emoji: '👀' },
  { id: 'gift', label: 'BONUS', emoji: '🎁' },
  { id: 'clock', label: 'TIME', emoji: '⏱️' },
  { id: 'phone', label: 'MOBILE', emoji: '📱' },
  { id: 'laptop', label: 'PC', emoji: '💻' },
  { id: 'crown', label: 'KING', emoji: '👑' },
  { id: 'target2', label: 'AIM', emoji: '🏹' },
  { id: 'medal', label: 'BEST', emoji: '🥇' },
  { id: 'camera', label: 'SHOT', emoji: '📸' },
  { id: 'mic', label: 'VOICE', emoji: '🎙️' },
  { id: 'wave', label: 'FLOW', emoji: '🌊' },
  { id: 'planet', label: 'WORLD', emoji: '🌍' },
  { id: 'chartup', label: 'UP', emoji: '📊' },
  { id: 'chartdown', label: 'DOWN', emoji: '📉' },
  { id: 'bag', label: 'BUY', emoji: '👜' },
  { id: 'ticket', label: 'PASS', emoji: '🎟️' },
  { id: 'zap', label: 'POWER', emoji: '⚡️' },
  { id: 'lock', label: 'LOCK', emoji: '🔒' },
  { id: 'unlock', label: 'OPEN', emoji: '🔓' },
  { id: 'pin', label: 'PIN', emoji: '📌' },
  { id: 'map', label: 'MAP', emoji: '🗺️' },
  { id: 'gift2', label: 'FREE', emoji: '🆓' },
  { id: 'bubble', label: 'CHAT', emoji: '💬' },
  { id: 'mail', label: 'MAIL', emoji: '✉️' },
  { id: 'cart', label: 'CART', emoji: '🛒' },
  { id: 'globe', label: 'WEB', emoji: '🌐' },
  { id: 'shield', label: 'SAFE', emoji: '🛡️' },
  { id: 'tool', label: 'TOOL', emoji: '🛠️' },
  { id: 'light', label: 'IDEA+', emoji: '🔆' },
  { id: 'diamond', label: 'VIP', emoji: '🔷' },
  { id: 'heart', label: 'LOVE', emoji: '❤️' },
  { id: 'flash', label: 'FLASH', emoji: '📍' },
  { id: 'focus', label: 'FOCUS', emoji: '🎥' },
  { id: 'viral', label: 'VIRAL', emoji: '🧲' },
  { id: 'loop', label: 'LOOP', emoji: '🔁' },
  { id: 'boost', label: 'BOOST', emoji: '🚀' },
  { id: 'story', label: 'STORY', emoji: '📚' },
  { id: 'pulse', label: 'PULSE', emoji: '💓' },
  { id: 'edge', label: 'EDGE', emoji: '📐' },
  { id: 'shine', label: 'SHINE', emoji: '🌟' },
  { id: 'clip', label: 'CLIP', emoji: '🎬' },
  { id: 'sync', label: 'SYNC', emoji: '🎼' },
  { id: 'social', label: 'SOCIAL', emoji: '📲' },
  { id: 'trend2', label: 'TREND+', emoji: '📣' },
  { id: 'target3', label: 'GOAL+', emoji: '🎯' },
  { id: 'sale2', label: 'DEAL', emoji: '🏷️' },
  { id: 'impact', label: 'IMPACT', emoji: '💢' },
  { id: 'signal', label: 'SIGNAL', emoji: '📡' },
  { id: 'filter', label: 'FILTER', emoji: '🧪' },
  { id: 'edit', label: 'EDIT', emoji: '📝' },
  { id: 'spark2', label: 'GLOW', emoji: '💫' },
]

export const TEXT_PRESET_SUGGESTIONS = [
  'Gancho fuerte en 3 segundos',
  'Antes de seguir mira esto',
  'El error que casi todos cometen',
  'Mira cómo cambia el resultado',
  'Texto secundario editable',
  'Llamada a la acción clara y corta',
  'Subtítulo potente y visible',
  'Comparativa rápida antes y después',
  'Oferta directa sin rodeos',
  'Tutorial corto paso a paso',
  'Reacción en grande arriba',
  'Frase final para cerrar el clip',
  'No hagas esto si quieres vender',
  'Tres puntos que cambian todo',
  'Lo mejor está al final',
  'Así se ve mucho mejor',
  'Lo que nadie te explica bien',
  'En menos de un minuto',
  'Esto te puede ahorrar tiempo',
  'El paso que marca la diferencia',
  'Hazlo así y cambia el resultado',
  'La forma rápida de empezar',
  'Plantilla lista para escalar contenido',
  'Cierre corto con llamada fuerte',
  'Empieza con impacto visual',
  'No pases sin mirar esto',
  'Te resumo lo importante',
  'Haz scroll más lento aquí',
  'Resultado rápido y limpio',
  'Esto sí cambia la percepción',
  'La versión que mejor funciona',
  'Lo que debes evitar hoy',
  'Mira este detalle de cerca',
  'Comparación clara y directa',
  'Así se estructura mejor',
  'No necesitas hacerlo más difícil',
  'Te enseño el truco rápido',
  'Este bloque retiene más',
  'Hazlo corto pero potente',
  'El cambio está en el orden',
  'Crea tensión al principio',
  'Cierra con una llamada clara',
  'Abre con una promesa fuerte',
  'Un ejemplo vale más que mil palabras',
  'Este formato engancha mejor',
  'Usa este cierre para convertir',
  'La prueba está en pantalla',
  'Esto se entiende al instante',
  'El ritmo importa más de lo que parece',
  'Quédate hasta el final',
  'Lo mejor viene ahora',
  'Te va a ahorrar trabajo',
  'Así ordenas mejor el contenido',
  'Muestra primero el resultado',
  'Hazlo simple y contundente',
  'Lo que sí conviene repetir',
  'Ahora mira la diferencia',
  'Un paso, un mensaje, un impacto',
  'Esta parte no la saltes',
  'Tu hook decide todo aquí',
  'Haz que se entienda en un vistazo',
  'Primero enseña el cambio',
  'Aquí empieza la parte buena',
  'Haz la prueba con este bloque',
  'Mete claridad antes que ruido',
  'Esto mejora la retención',
  'Sube el ritmo en este punto',
  'Quita lo que no aporta',
  'Haz visual la promesa',
  'Empieza limpio, cierra fuerte',
  'Pon el beneficio primero',
  'El espectador debe verlo ya',
  'Hazlo más corto y más claro',
  'Convierte esto en una serie',
  'Esta apertura vende mejor',
  'Hazlo sonar y verse premium',
  'Menos texto, más impacto',
  'Este tramo pide más energía',
  'Corta aquí para ganar ritmo',
  'Aquí va el detalle que engancha',
  'Pon el resultado en pantalla',
  'Repite solo lo que suma',
  'Haz que el cierre empuje acción',
]
